apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.jwtSecretKey | default "change-me-in-prod" | quote }}
  ADMIN_USERNAME: {{ .Values.adminUsername | default "admin" | quote }}
  ADMIN_EMAIL: {{ .Values.adminEmail | default "admin@household.com" | quote }}
  ADMIN_PASSWORD: {{ .Values.adminPassword | default "admin123" | quote }}
  ADMIN_FULL_NAME: {{ .Values.adminFullName | default "Super Admin" | quote }}